import { UserSecretsMutation, UserSecretsQuery } from '@newrelic/nr1-community';
import {
  UserStorageMutation,
  UserStorageQuery,
  AccountStorageQuery,
} from 'nr1';
import React from 'react';
import PropTypes from 'prop-types';
import { id } from '../../../nr1.json';
import { accountId } from '../../../deploy-settings.json';

/** Increment this value when changing the schema of the data in nerdstorage */
const DASHBOARD_MAJOR_VERSION = 2;
const GH_TOKEN_KEY = `${id}-githubToken-v1`;
const SETTINGS_KEY = `${id}-ospoSettings-v1`;
const EMPLOYEE_METADATA_ACCOUNT_ID = accountId;
const EMPLOYEE_METADATA_COLLECTION = `${id}-employeeMetadata-v1`;
const EMPLOYEE_METADATA_DOCUMENT = EMPLOYEE_METADATA_COLLECTION;

/**
 * Component used to read and write the NerdStorage values relevant to this
 * dashboard. Similar to the existing NerdStorage components, this component
 * works both declaratively (as a component) and imperatively (static
 * functions).
 */
export default class SettingsQuery extends React.Component {
  /**
   * Remove the PAT from NerdVault.
   *
   * @returns {Promise<void>}
   */
  static async removeToken() {
    await UserSecretsMutation.mutate({
      actionType: UserSecretsMutation.ACTION_TYPE.DELETE_SECRET,
      name: GH_TOKEN_KEY,
    });
  }

  /**
   * Read the PAT from NerdVault.
   *
   * @returns {Promise<?string>} The PAT, or falsey if the token does not exist.
   */
  static async readToken() {
    const { data } = await UserSecretsQuery.query({
      name: GH_TOKEN_KEY,
    });
    return data?.value;
  }

  /**
   * Save the PAT to NerdVault
   *
   * @returns {Promise<void>}
   */
  static async writeToken(token) {
    await UserSecretsMutation.mutate({
      actionType: UserSecretsMutation.ACTION_TYPE.WRITE_SECRET,
      name: GH_TOKEN_KEY,
      value: token,
    });
  }

  /**
   * @typedef {Object} Profile An object contains the settings for a
   *     single dashboard profile.
   * @property {string[]} settings.repos A list of repositories including the
   *     owner to scan. (`owner/repo`).
   * @property {string[]} settings.labels A list of Issue/PR labels to denylist.
   * @property {string[]} settings.users A list of GitHub logins to include in
   *     the employee list.
   * @property {number} settings.staleTimeValue A count of how many
   *     staleTimeUnits to use for the stale time.
   * @property {number} settings.staleTimeUnit The number of milliseconds per
   *     staleTimeValue count.
   * @property {string} settings.profileName The name of the profile, human
   *     readable.
   */

  /**
   * Checks the major version of a given settings document, and performs any
   * needed translation if the settings are old.
   *
   * @private
   * @param {any} settings
   * @returns {?{
   *   profiles: Profile[];
   *   currentProfileIndex: number;
   * }} The
   *     translated settings object.
   */
  static async translateSettings(settings) {
    if (!settings.version) {
      return {
        profileList: [
          {
            ...settings,
            profileName: 'Autogenerated Profile Name',
            staleTimeValue: settings.staleTime / (1000 * 60),
            staleTimeUnit: 1000 * 60,
          },
        ],
        currentProfileIndex: 0,
      };
    }
    return settings;
  }

  /**
   * Write user settings to NerdStorage. Shallow merges the settings parameter
   * with the current user settings, allowing incremental updates.
   *
   * @param {?Profile[]} settings.profileList A list of profiles to save to
   *     persistent storage.
   * @param {?number} settings.currentProfileIndex The index of the current
   *     profile
   *     that the dashboard has selected.
   * @returns {Promise<void>}
   */
  static async writeSettings(settings) {
    if (
      !settings ||
      (!settings.profileList &&
        typeof settings.currentProfileIndex !== 'number')
    )
      return;
    // read, merge, then write
    let newSettings;
    if (
      !settings.profileList ||
      typeof settings.currentProfileIndex !== 'number'
    ) {
      const oldSettings = await SettingsQuery.readSettings();
      newSettings = {
        ...SettingsQuery.DEFAULT_SETTINGS,
        ...oldSettings,
        ...settings,
      };
    } else newSettings = settings;
    await UserStorageMutation.mutate({
      actionType: UserStorageMutation.ACTION_TYPE.WRITE_DOCUMENT,
      collection: SETTINGS_KEY,
      documentId: SETTINGS_KEY,
      document: {
        ...newSettings,
        version: DASHBOARD_MAJOR_VERSION,
      },
    });
  }

  /**
   * Read user settings from NerdStorage
   *
   * @returns {Promise<
   *   ?{
   *     profileList: Profile[];
   *     currentProfileIndex: string;
   *   }
   * >}
   *     An array containing the stored
   *     user settings.
   */
  static async readSettings() {
    const { data } = await UserStorageQuery.query({
      collection: SETTINGS_KEY,
      documentId: SETTINGS_KEY,
    });
    if (!data) return data;
    // translate between version 1 and version 2 data if needed
    return SettingsQuery.translateSettings(data);
  }

  /**
   * Read employee metadata from account-based nerdstorage. At the moment this
   * returns an array of usernames associated with the current company.
   *
   * @returns {Promise<string[]>} An array of usernames, or an empty array of
   *     none were found.
   */
  static async readEmployeeData() {
    const { data } = await AccountStorageQuery.query({
      accountId: EMPLOYEE_METADATA_ACCOUNT_ID,
      collection: EMPLOYEE_METADATA_COLLECTION,
      documentId: EMPLOYEE_METADATA_DOCUMENT,
    });
    return data?.users;
  }

  static propTypes = {
    /** ({ loading, token, settings, users }) => JSX */
    children: PropTypes.func.isRequired,
  };

  constructor(props = {}) {
    super(props);
    this.state = {
      loading: true,
    };
  }

  async componentDidMount() {
    const [token, settings, users] = await Promise.all([
      SettingsQuery.readToken(),
      SettingsQuery.readSettings(),
      SettingsQuery.readEmployeeData(),
    ]);
    this.setState({
      loading: false,
      token,
      settings,
      users,
    });
  }

  /** Default values for a profile in the settings */
  static DEFAULT_PROFILE = {
    repos: ['newrelic/nr1-ospo'],
    labels: [],
    users: [],
    staleTimeValue: 2,
    staleTimeUnit: 1000 * 60 * 60 * 24 * 7, // weeks
    profileName: 'Profile Name',
  };

  /** Default values for the user settings */
  static DEFAULT_SETTINGS = {
    currentProfileIndex: 0,
    profileList: [SettingsQuery.DEFAULT_PROFILE],
  };

  render() {
    return this.props.children(this.state);
  }
}
